"use strict";
const root=document.getElementById("app");
const boot=JSON.parse(root.dataset.bootstrap||"{}");
const token=boot.token||"";
let state=null, stream=null;
const titles={overview:"نظرة عامة",agents:"الوكلاء والمهام",models:"النماذج والحصص",approvals:"مركز الموافقات",memory:"الذاكرة والمعرفة",science:"المختبر العلمي",git:"Git والدمج",sandbox:"Sandbox والموارد",audit:"سجل التدقيق"};
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const status=v=>`<span class="status ${esc(v||"neutral")}">${esc(v||"unknown")}</span>`;
const shortTime=v=>{if(!v)return"—";try{return new Date(v).toLocaleString("ar-DZ",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}catch{return v}};
const bytes=v=>{if(v==null)return"—";const n=Number(v);if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`};
const setHTML=(id,html)=>{const el=document.getElementById(id);if(el)el.innerHTML=html};
function toast(message,error=false){const el=document.getElementById("toast");el.textContent=message;el.className=`toast${error?" error":""}`;setTimeout(()=>el.classList.add("hidden"),2800)}
async function api(path,options={}){const headers={...(options.headers||{}),Authorization:`Bearer ${token}`};if(options.body)headers["Content-Type"]="application/json";const r=await fetch(path,{...options,headers});const data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function activate(view){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===view));document.getElementById(`view-${view}`).classList.add("active");document.getElementById("page-title").textContent=titles[view];history.replaceState(null,"",`#${view}`)}
function metricCards(m){const defs=[["sessions","الجلسات","سجلات بروتوكول موثوقة","#72f1d1"],["active_runs","التشغيلات النشطة","Orchestrator","#7794ff"],["active_agents","الوكلاء النشطون","Parallel runtime","#f7c56e"],["pending_approvals","الموافقات المنتظرة","Human control","#ff7587"],["memory_records","سجلات الذاكرة","Knowledge Fabric","#86d7ff"],["scientific_studies","الدراسات العلمية","Verification Lab","#b39bff"],["sandbox_executions","تنفيذات Sandbox","Secure Fabric","#6ee7a8"],["tool_calls","استدعاءات الأدوات","MCP Registry","#ffad75"]];return defs.map(([k,l,n,c])=>`<article class="metric-card" style="--glow:${c}"><div class="metric-label">${l}</div><div class="metric-value">${m[k]??0}</div><div class="metric-note">${n}</div></article>`).join("")}
function currentRun(){return(state?.runs||[])[0]||null}
function graphHTML(tasks,large=false){if(!tasks?.length)return'<div class="empty-state">لا توجد مهام في التشغيل الحالي.</div>';return tasks.map((t,i)=>`${i?'<span class="graph-arrow">←</span>':''}<div class="agent-node"><i class="node-state ${["failed","cancelled"].includes(t.status)?"failed":["pending","created","blocked"].includes(t.status)?"waiting":""}"></i><div class="avatar">${esc((t.task_id||"T").slice(0,2).toUpperCase())}</div><b>${esc(t.task_id)}</b><small>${esc(t.resource_id||"بانتظار المورد")}</small><small>${esc(t.status)}</small></div>`).join("")}
function providerRows(items,limit=99){if(!items?.length)return'<div class="empty-state">لم تسجل موارد نموذج بعد.</div>';return items.slice(0,limit).map(p=>{const max=Number(p.limit_units||0),rem=Number(p.remaining_units??0),pct=max?Math.max(0,Math.min(100,rem/max*100)):p.quota_status==="exhausted"?0:60;return`<div class="provider-row"><div class="provider-top"><div><b>${esc(p.model||p.resource_id)}</b><span>${esc(p.provider||"")}</span></div>${status(p.quota_status)}</div><div class="quota-track"><i style="width:${pct}%"></i></div><div class="memory-foot"><span>${p.remaining_units==null?"الحصة غير معروفة":`${esc(p.remaining_units)} متبقية`}</span><span>${p.reset_at?`إعادة الضبط ${shortTime(p.reset_at)}`:""}</span></div></div>`}).join("")}
function timeline(items,limit=99){if(!items?.length)return'<div class="empty-state">لا توجد أحداث بعد.</div>';return items.slice(0,limit).map(e=>`<div class="timeline-item"><i class="dot"></i><div><b>${esc(e.type||e.subject)}</b><p>${esc(e.subject||"")} ${e.detail?`— ${esc(e.detail)}`:""}</p></div><time>${shortTime(e.time)}</time></div>`).join("")}
function renderOverview(){const m=state.metrics||{};setHTML("metric-grid",metricCards(m));const run=currentRun();setHTML("run-state",run?status(run.status):status("neutral"));setHTML("agent-graph",graphHTML(run?.tasks));setHTML("task-progress",(run?.tasks||[]).map(t=>`<i class="${["completed","accepted","succeeded"].includes(t.status)?"done":["running","in_progress"].includes(t.status)?"active":""}"></i>`).join(""));setHTML("health-list",(state.health||[]).map(h=>`<div class="health-item"><div><i></i><span>${esc(h.component)}</span></div><small>${esc(h.detail)}</small></div>`).join(""));setHTML("provider-preview",providerRows(state.providers,4));setHTML("audit-preview",timeline(state.audit,7));const f=state.final_result;if(!f){setHTML("final-result",'<div class="empty-state">ستظهر هنا النتيجة الموحدة عند اكتمال أول تشغيل.</div>');setHTML("final-status",status("neutral"));}else{const payload=f.payload||f;const rs=payload.result_status||payload.status||"published";setHTML("final-status",status(rs));setHTML("final-result",`<div class="result-main"><h3>${esc(payload.title||payload.summary?.title||"FinalResult")}</h3><p>${esc(payload.summary?.text||payload.summary||payload.description||"نتيجة موحدة موثقة من W1 Nexus.")}</p></div><div class="result-stat"><span>الحالة</span><b>${esc(rs)}</b></div><div class="result-stat"><span>القرارات</span><b>${(payload.accepted_decisions||payload.decisions||[]).length||0}</b></div><div class="result-stat"><span>الادعاءات المثبتة</span><b>${(payload.verified_claims||[]).length||0}</b></div>`)} }
function renderAgents(){const run=currentRun(),tasks=run?.tasks||[];setHTML("full-agent-graph",graphHTML(tasks,true));const allJobs=state.agents?.jobs||[];setHTML("agent-summary",`<span>${allJobs.length} وكيل مسجل</span><span>${allJobs.filter(x=>x.status==="running").length} يعمل الآن</span><span>${state.agents?.runs?.length||0} تشغيل متوازٍ</span>`);setHTML("parallel-runs",(state.agents?.runs||[]).map(r=>`<div class="stack-row"><div class="stack-top"><b>${esc(r.run_id)}</b>${status(r.status)}</div><div class="memory-foot"><span>${esc(r.target_branch)}</span><span>${shortTime(r.created_at)}</span></div></div>`).join("")||'<div class="empty-state">لا توجد تشغيلات متوازية.</div>');setHTML("task-table",tasks.map(t=>`<tr><td>${esc(t.task_id)}</td><td>${esc(t.agent_id||t.resource_id||"—")}</td><td>${status(t.status)}</td><td>${esc(t.resource_id||"—")}</td><td>${esc(t.attempts||0)}</td><td>${t.requires_extra_review?"مطلوبة":"—"}</td></tr>`).join("")||'<tr><td colspan="6" class="empty-state">لا توجد مهام.</td></tr>')}
function renderModels(){setHTML("model-grid",(state.providers||[]).map(p=>`<article class="model-card"><div class="model-head"><div class="model-logo">AI</div><div><b>${esc(p.model||p.resource_id)}</b><small>${esc(p.provider||p.resource_id)}</small></div></div>${providerRows([p])}<div class="model-meta"><div><span>Fitness</span><b>${p.fitness_score??"—"}</b></div><div><span>Reserved</span><b>${p.reserved_units??0}</b></div></div></article>`).join("")||'<div class="empty-state">لا توجد موارد معرفة.</div>')}
function renderApprovals(){const items=state.approvals||[];setHTML("approval-badge",items.length?String(items.length):"0");document.getElementById("approval-badge").classList.toggle("hidden",!items.length);setHTML("operations-mode",status(boot.allowOperations?"active":"neutral"));setHTML("approval-list",items.map(a=>`<div class="approval-row"><div><div class="approval-top"><b>${esc(a.subject)}</b>${status(a.risk)}</div><p>${esc(a.source)} · أصدرها ${esc(a.issued_by||"غير معروف")} · تنتهي ${shortTime(a.expires_at)}</p></div><button class="button secondary" disabled>مقيدة بالـCLI</button></div>`).join("")||'<article class="panel empty-state">لا توجد موافقات معلقة.</article>')}
function renderMemory(){const mem=state.memory||{counts:{},records:[]};setHTML("memory-counters",`<span>${mem.counts.total||0} سجل</span><span>${mem.counts.open_conflicts||0} تعارض مفتوح</span>`);filterMemory()}
function filterMemory(){if(!state)return;const q=(document.getElementById("memory-search")?.value||"").toLowerCase(),kind=document.getElementById("memory-filter")?.value||"all";const rows=(state.memory?.records||[]).filter(r=>(kind==="all"||r.kind===kind)&&JSON.stringify(r).toLowerCase().includes(q));setHTML("memory-list",rows.map(r=>`<article class="memory-card"><span class="memory-type">${esc(r.kind)}</span><h3>${esc(r.summary||r.canonical_key)}</h3><p>${esc(r.subject)} · ${esc(r.predicate)}</p><div class="memory-foot"><span>ثقة ${Math.round(Number(r.confidence||0)*100)}%</span><span>${esc(r.sensitivity)} / ${esc(r.visibility)}</span></div></article>`).join("")||'<div class="empty-state">لا توجد نتائج مطابقة.</div>')}
function renderScience(){setHTML("science-list",(state.science?.studies||[]).map(s=>`<article class="science-card"><div class="provider-top"><span class="status ${esc(s.status)}">${esc(s.status)}</span><small>${shortTime(s.updated_at)}</small></div><h3>${esc(s.title)}</h3><p>${esc(s.study_id)}</p><div class="science-stats"><span>${s.observations||0} ملاحظة</span><span>${s.analyses||0} تحليل</span><span>${s.review?esc(s.review.outcome):"دون مراجعة"}</span></div></article>`).join("")||'<div class="empty-state">لم تنشأ دراسات بعد.</div>')}
function renderGit(){const g=state.git||{};setHTML("git-status-pill",g.available?status(g.dirty?"blocked":"online"):status("neutral"));setHTML("merge-list",(state.merges||[]).map(m=>`<div class="stack-row"><div class="stack-top"><b>${esc(m.proposal_id)}</b>${status(m.status)}</div><div class="memory-foot"><span>${esc(m.target_branch||"—")}</span><span>${m.review?`مراجعة: ${esc(m.review.outcome||"مسجلة")}`:"بانتظار المراجعة"}</span></div></div>`).join("")||'<div class="empty-state">لا توجد مقترحات دمج.</div>');setHTML("commit-list",timeline((g.commits||[]).map(c=>({type:c.subject,subject:`${c.sha} · ${c.author}`,time:c.time})),10));document.getElementById("git-changes").textContent=(g.changes||[]).join("\n")||"لا توجد تغييرات."}
function renderSandbox(){setHTML("sandbox-table",(state.sandboxes||[]).map(s=>`<tr><td>${esc(s.execution_id)}</td><td>${esc(s.profile_id)}</td><td>${esc(s.backend||"—")}</td><td>${status(s.status)}</td><td>${s.wall_seconds==null?"—":`${Number(s.wall_seconds).toFixed(2)}s`}</td><td>${bytes(s.peak_rss_bytes)}</td><td>${s.artifact_count||0}</td></tr>`).join("")||'<tr><td colspan="7" class="empty-state">لا توجد تنفيذات Sandbox.</td></tr>')}
function renderAudit(){const f=document.getElementById("audit-filter")?.value||"all";setHTML("audit-list",timeline((state.audit||[]).filter(x=>f==="all"||x.source===f),100))}
function renderAll(){document.getElementById("loading").classList.add("hidden");renderOverview();renderAgents();renderModels();renderApprovals();renderMemory();renderScience();renderGit();renderSandbox();renderAudit();document.getElementById("console-version").textContent=`${boot.consoleVersion} · ${state.workspace?.name||"W1"}`}
async function refresh(){try{state=await api("/api/snapshot");renderAll();connected(true)}catch(e){connected(false);toast(e.message,true)}}
function connected(ok){const dot=document.getElementById("connection-dot"),label=document.getElementById("connection-label");dot.className=ok?"online":"offline";label.textContent=ok?"متصل بالبث الحي":"انقطع الاتصال"}
function startStream(){if(stream)stream.close();stream=new EventSource(`/api/stream?token=${encodeURIComponent(token)}`);stream.addEventListener("snapshot",e=>{state=JSON.parse(e.data);renderAll();connected(true)});stream.onerror=()=>connected(false);stream.onopen=()=>connected(true)}
async function operation(name,payload={}){try{const r=await api("/api/operation",{method:"POST",body:JSON.stringify({operation:name,...payload})});toast("اكتملت العملية بنجاح");await refresh();return r}catch(e){toast(e.message,true)}}
document.getElementById("nav").addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(b)activate(b.dataset.view)});document.body.addEventListener("click",e=>{const b=e.target.closest("[data-go]");if(b)activate(b.dataset.go)});document.getElementById("refresh").addEventListener("click",refresh);document.getElementById("verify-all").addEventListener("click",()=>operation("verify_all_sessions"));document.getElementById("memory-search").addEventListener("input",filterMemory);document.getElementById("memory-filter").addEventListener("change",filterMemory);document.getElementById("audit-filter").addEventListener("change",renderAudit);document.getElementById("global-search").addEventListener("input",e=>{const q=e.target.value.toLowerCase();document.querySelectorAll(".view.active .panel,.view.active .metric-card,.view.active .model-card,.view.active .memory-card,.view.active .science-card").forEach(el=>el.style.display=!q||el.textContent.toLowerCase().includes(q)?"":"none")});
activate(location.hash.slice(1) in titles?location.hash.slice(1):"overview");refresh();startStream();
